theme: jekyll-theme-minimal
title: "Leandro Aristeguieta"
description: "PhD Student, History Department Department, Indiana University-Bloomington"
logo: /assets/img/aristeguieta-leandro.jpg
author: "Leandro Aristeguieta"
