theme: jekyll-theme-minimal
title: "Leandro Aristeguieta"
description: "PhD Student, History Department Department, Indiana University-Bloomington"
logo: /assets/headshotsmall.jpg
author: "Leandro Aristeguieta"
include:
  - CV.md
collections:
  pages:
    output: true
permalink: pretty
